<?php

return array(
  'aa' => array(
    'title' => 'Afaraf',
    'title_en' => 'Afar',
    'title_ru' => 'Афарский',
    'locale' => 'aa_DJ',
    'locales' => array('aa_DJ','aa_ER','aa_ET'),
    'month' => array( 1 =>
      'Qunxa Garablu',
      'Kudo',
      'Ciggilta Kudo',
      'Agda Baxis',
      'Caxah Alsa',
      'Qasa Dirri',
      'Qado Dirri',
      'Liiqen',
      'Waysu',
      'Diteli',
      'Ximoli',
      'Kaxxa Garablu',
    ),
  ),
  'af' => array(
    'title' => 'Afrikaans',
    'title_en' => 'Afrikaans',
    'title_ru' => 'Африкаанс',
    'locale' => 'af_ZA',
    'locales' => array('af_ZA'),
    'month' => array( 1 =>
      'Januarie',
      'Februarie',
      'Maart',
      'April',
      'Mei',
      'Junie',
      'Julie',
      'Augustus',
      'September',
      'Oktober',
      'November',
      'Desember',
    ),
  ),
  'am' => array(
    'title' => 'አማርኛ',
    'title_en' => 'Amharic',
    'title_ru' => 'Амхарский',
    'locale' => 'am_ET',
    'locales' => array('am_ET'),
    'month' => array( 1 =>
      'ጃንዩወሪ',
      'ፌብሩወሪ',
      'ማርች',
      'ኤፕሪል',
      'ሜይ',
      'ጁን',
      'ጁላይ',
      'ኦገስት',
      'ሴፕቴምበር',
      'ኦክቶበር',
      'ኖቬምበር',
      'ዲሴምበር',
    ),
  ),
  'ar' => array(
    'title' => 'العربية',
    'title_en' => 'Arabic',
    'title_ru' => 'Арабский',
    'locale' => 'ar_AE',
    'locales' => array('ar_AE','ar_BH','ar_DZ','ar_EG','ar_IN','ar_IQ','ar_JO','ar_KW','ar_LB','ar_LY','ar_MA','ar_OM','ar_QA','ar_SA','ar_SD','ar_SY','ar_TN','ar_YE'),
    'month' => array( 1 =>
      'يناير',
      'فبراير',
      'مارس',
      'أبريل',
      'مايو',
      'يونيو',
      'يوليو',
      'أغسطس',
      'سبتمبر',
      'أكتوبر',
      'نوفمبر',
      'ديسمبر',
    ),
  ),
  'as' => array(
    'title' => 'অসমীয়া',
    'title_en' => 'Assamese',
    'title_ru' => 'Ассамский',
    'locale' => 'as_IN',
    'locales' => array('as_IN'),
    'month' => array( 1 =>
      'জানুৱাৰী',
      'ফেব্ৰুৱাৰী',
      'মাৰ্চ',
      'এপ্ৰিল',
      'মে',
      'জুন',
      'জুলাই',
      'আগষ্ট',
      'ছেপ্তেম্বৰ',
      'অক্টোবৰ',
      'নৱেম্বৰ',
      'ডিচেম্বৰ',
    ),
  ),
  'az' => array(
    'title' => 'Azərbaycan dili',
    'title_en' => 'Azerbaijani',
    'title_ru' => 'Азербайджанский',
    'locale' => 'az_AZ',
    'locales' => array('az_AZ'),
    'month' => array( 1 =>
      'Yanvar',
      'Fevral',
      'Mart',
      'Aprel',
      'May',
      'İyun',
      'İyul',
      'Avqust',
      'Sentyabr',
      'Oktyabr',
      'Noyabr',
      'Dekabr',
    ),
  ),
  'be' => array(
    'title' => 'Беларуская',
    'title_en' => 'Belarusian',
    'title_ru' => 'Белорусский',
    'locale' => 'be_BY',
    'locales' => array('be_BY'),
    'month' => array( 1 =>
      'студзень',
      'люты',
      'сакавік',
      'красавік',
      'травень',
      'чэрвень',
      'ліпень',
      'жнівень',
      'верасень',
      'кастрычнік',
      'лістапад',
      'снежань',
    ),
  ),
  'bg' => array(
    'title' => 'Български',
    'title_en' => 'Bulgarian',
    'title_ru' => 'Болгарский',
    'locale' => 'bg_BG',
    'locales' => array('bg_BG'),
    'month' => array( 1 =>
      'януари',
      'февруари',
      'март',
      'април',
      'май',
      'юни',
      'юли',
      'август',
      'септември',
      'октомври',
      'ноември',
      'декември',
    ),
  ),
  'bn' => array(
    'title' => 'বাংলা',
    'title_en' => 'Bengali',
    'title_ru' => 'Бенгальский',
    'locale' => 'bn_BD',
    'locales' => array('bn_BD','bn_IN'),
    'month' => array( 1 =>
      'জানুয়ারী',
      'ফেব্রুয়ারী',
      'মার্চ',
      'এপ্রিল',
      'মে',
      'জুন',
      'জুলাই',
      'আগস্ট',
      'সেপ্টেম্বর',
      'অক্টোবর',
      'নভেম্বর',
      'ডিসেম্বর',
    ),
  ),
  'bo' => array(
    'title' => 'བོད་ཡིག',
    'title_en' => 'Tibetan',
    'title_ru' => 'Тибетский',
    'locale' => 'bo_CN',
    'locales' => array('bo_CN','bo_IN'),
    'month' => array( 1 =>
      'ཟླ་བ་དང་པོ་',
      'ཟླ་བ་གཉིས་པ་',
      'ཟླ་བ་སུམ་པ་',
      'ཟླ་བ་བཞི་པ་',
      'ཟླ་བ་ལྔ་པ་',
      'ཟླ་བ་དྲུག་པ་',
      'ཟླ་བ་བདུན་པ་',
      'ཟླ་བ་བརྒྱད་པ་',
      'ཟླ་བ་དགུ་པ་',
      'ཟླ་བ་བཅུ་པ་',
      'ཟླ་བ་བཅུ་གཅིག་པ་',
      'ཟླ་བ་བཅུ་གཉིས་པ་',
    ),
  ),
  'br' => array(
    'title' => 'Brezhoneg',
    'title_en' => 'Breton',
    'title_ru' => 'Бретонский',
    'locale' => 'br_FR',
    'locales' => array('br_FR'),
    'month' => array( 1 =>
      'Genver',
      'Cʼhwevrer',
      'Meurzh',
      'Ebrel',
      'Mae',
      'Mezheven',
      'Gouere',
      'Eost',
      'Gwengolo',
      'Here',
      'Du',
      'Kerzu',
    ),
  ),
  'bs' => array(
    'title' => 'Bosanski',
    'title_en' => 'Bosnian',
    'title_ru' => 'Боснийский',
    'locale' => 'bs_BA',
    'locales' => array('bs_BA'),
    'month' => array( 1 =>
      'januar',
      'februar',
      'mart',
      'april',
      'maj',
      'juni',
      'juli',
      'avgust',
      'septembar',
      'oktobar',
      'novembar',
      'decembar',
    ),
  ),
  'ca' => array(
    'title' => 'Català',
    'title_en' => 'Catalan; Valencian',
    'title_ru' => 'Каталанский',
    'locale' => 'ca_AD',
    'locales' => array('ca_AD','ca_ES','ca_FR','ca_IT'),
    'month' => array( 1 =>
      'gener',
      'febrer',
      'març',
      'abril',
      'maig',
      'juny',
      'juliol',
      'agost',
      'setembre',
      'octubre',
      'novembre',
      'desembre',
    ),
  ),
  'cs' => array(
    'title' => 'Česky',
    'title_en' => 'Czech',
    'title_ru' => 'Чешский',
    'locale' => 'cs_CZ',
    'locales' => array('cs_CZ'),
    'month' => array( 1 =>
      'leden',
      'únor',
      'březen',
      'duben',
      'květen',
      'červen',
      'červenec',
      'srpen',
      'září',
      'říjen',
      'listopad',
      'prosinec',
    ),
  ),
  'cy' => array(
    'title' => 'Cymraeg',
    'title_en' => 'Welsh',
    'title_ru' => 'Валлийский',
    'locale' => 'cy_GB',
    'locales' => array('cy_GB'),
    'month' => array( 1 =>
      'Ionawr',
      'Chwefror',
      'Mawrth',
      'Ebrill',
      'Mai',
      'Mehefin',
      'Gorffennaf',
      'Awst',
      'Medi',
      'Hydref',
      'Tachwedd',
      'Rhagfyr',
    ),
  ),
  'da' => array(
    'title' => 'Dansk',
    'title_en' => 'Danish',
    'title_ru' => 'Датский',
    'locale' => 'da_DK',
    'locales' => array('da_DK'),
    'month' => array( 1 =>
      'januar',
      'februar',
      'marts',
      'april',
      'maj',
      'juni',
      'juli',
      'august',
      'september',
      'oktober',
      'november',
      'december',
    ),
  ),
  'de' => array(
    'title' => 'Deutsch',
    'title_en' => 'German',
    'title_ru' => 'Немецкий',
    'locale' => 'de_DE',
    'locales' => array('de_AT','de_BE','de_CH','de_DE','de_LU'),
    'month' => array( 1 =>
      'Januar',
      'Februar',
      'März',
      'April',
      'Mai',
      'Juni',
      'Juli',
      'August',
      'September',
      'Oktober',
      'November',
      'Dezember',
    ),
  ),
  'dv' => array(
    'title' => 'ދިވެހި',
    'title_en' => 'Divehi; Dhivehi; Maldivian;',
    'title_ru' => 'Дивехи (Мальдивский)',
    'locale' => 'dv_MV',
    'locales' => array('dv_MV'),
    'month' => array( 1 =>
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
    ),
  ),
  'el' => array(
    'title' => 'Ελληνικά',
    'title_en' => 'Greek, Modern',
    'title_ru' => 'Греческий',
    'locale' => 'el_GR',
    'locales' => array('el_CY','el_GR'),
    'month' => array( 1 =>
      'Ιανουάριος',
      'Φεβρουάριος',
      'Μάρτιος',
      'Απρίλιος',
      'Μάιος',
      'Ιούνιος',
      'Ιούλιος',
      'Αύγουστος',
      'Σεπτέμβριος',
      'Οκτώβριος',
      'Νοέμβριος',
      'Δεκέμβριος',
    ),
  ),
  'en' => array(
    'title' => 'English',
    'title_en' => 'English',
    'title_ru' => 'Английский',
    'locale' => 'en_US',
    'locales' => array('en_AG','en_AU','en_BW','en_CA','en_DK','en_GB','en_HK','en_IE','en_IN','en_NG','en_NZ','en_PH','en_SG','en_US','en_ZA','en_ZM','en_ZW'),
    'month' => array( 1 =>
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ),
  ),
  'es' => array(
    'title' => 'Español',
    'title_en' => 'Spanish',
    'title_ru' => 'Испанский',
    'locale' => 'es_ES',
    'locales' => array('es_AR','es_BO','es_CL','es_CO','es_CR','es_CU','es_DO','es_EC','es_ES','es_GT','es_HN','es_MX','es_NI','es_PA','es_PE','es_PR','es_PY','es_SV','es_US','es_UY','es_VE'),
    'month' => array( 1 =>
      'enero',
      'febrero',
      'marzo',
      'abril',
      'mayo',
      'junio',
      'julio',
      'agosto',
      'septiembre',
      'octubre',
      'noviembre',
      'diciembre',
    ),
  ),
  'et' => array(
    'title' => 'Eesti',
    'title_en' => 'Estonian',
    'title_ru' => 'Эстонский',
    'locale' => 'et_EE',
    'locales' => array('et_EE'),
    'month' => array( 1 =>
      'jaanuar',
      'veebruar',
      'märts',
      'aprill',
      'mai',
      'juuni',
      'juuli',
      'august',
      'september',
      'oktoober',
      'november',
      'detsember',
    ),
  ),
  'eu' => array(
    'title' => 'Euskara',
    'title_en' => 'Basque',
    'title_ru' => 'Баскский',
    'locale' => 'eu_ES',
    'locales' => array('eu_ES'),
    'month' => array( 1 =>
      'urtarrila',
      'otsaila',
      'martxoa',
      'apirila',
      'maiatza',
      'ekaina',
      'uztaila',
      'abuztua',
      'iraila',
      'urria',
      'azaroa',
      'abendua',
    ),
  ),
  'fa' => array(
    'title' => 'فارسی',
    'title_en' => 'Persian',
    'title_ru' => 'Персидский',
    'locale' => 'fa_IR',
    'locales' => array('fa_IR'),
    'month' => array( 1 =>
      'ژانویه',
      'فوریه',
      'مارس',
      'آوریل',
      'مه',
      'ژوئن',
      'ژوئیه',
      'اوت',
      'سپتامبر',
      'اکتبر',
      'نوامبر',
      'دسامبر',
    ),
  ),
  'ff' => array(
    'title' => 'Fulfulde',
    'title_en' => 'Fula',
    'title_ru' => 'Фулах',
    'locale' => 'ff_SN',
    'locales' => array('ff_SN'),
    'month' => array( 1 =>
      'siilo',
      'colte',
      'mbooy',
      'seeɗto',
      'duujal',
      'korse',
      'morso',
      'juko',
      'siilto',
      'yarkomaa',
      'jolal',
      'bowte',
    ),
  ),
  'fi' => array(
    'title' => 'Suomi',
    'title_en' => 'Finnish',
    'title_ru' => 'Финский',
    'locale' => 'fi_FI',
    'locales' => array('fi_FI'),
    'month' => array( 1 =>
      'tammikuu',
      'helmikuu',
      'maaliskuu',
      'huhtikuu',
      'toukokuu',
      'kesäkuu',
      'heinäkuu',
      'elokuu',
      'syyskuu',
      'lokakuu',
      'marraskuu',
      'joulukuu',
    ),
  ),
  'fo' => array(
    'title' => 'Føroyskt',
    'title_en' => 'Faroese',
    'title_ru' => 'Фарерский',
    'locale' => 'fo_FO',
    'locales' => array('fo_FO'),
    'month' => array( 1 =>
      'januar',
      'februar',
      'mars',
      'apríl',
      'mai',
      'juni',
      'juli',
      'august',
      'september',
      'oktober',
      'november',
      'desember',
    ),
  ),
  'fr' => array(
    'title' => 'Français',
    'title_en' => 'French',
    'title_ru' => 'Французский',
    'locale' => 'fr_FR',
    'locales' => array('fr_BE','fr_CA','fr_CH','fr_FR','fr_LU'),
    'month' => array( 1 =>
      'janvier',
      'février',
      'mars',
      'avril',
      'mai',
      'juin',
      'juillet',
      'août',
      'septembre',
      'octobre',
      'novembre',
      'décembre',
    ),
  ),
  'ga' => array(
    'title' => 'Gaeilge',
    'title_en' => 'Irish',
    'title_ru' => 'Ирландский',
    'locale' => 'ga_IE',
    'locales' => array('ga_IE'),
    'month' => array( 1 =>
      'Eanáir',
      'Feabhra',
      'Márta',
      'Aibreán',
      'Bealtaine',
      'Meitheamh',
      'Iúil',
      'Lúnasa',
      'Meán Fómhair',
      'Deireadh Fómhair',
      'Samhain',
      'Nollaig',
    ),
  ),
  'gd' => array(
    'title' => 'Gàidhlig',
    'title_en' => 'Scottish Gaelic',
    'title_ru' => 'Гэльский',
    'locale' => 'gd_GB',
    'locales' => array('gd_GB'),
    'month' => array( 1 =>
      'Am Faoilleach',
      'An Gearran',
      'Am Màrt',
      'An Giblean',
      'An Cèitean',
      'An t-Ògmhios',
      'An t-Iuchar',
      'An Lùnastal',
      'An t-Sultain',
      'An Dàmhair',
      'An t-Samhain',
      'An Dùbhlachd',
    ),
  ),
  'gl' => array(
    'title' => 'Galego',
    'title_en' => 'Galician',
    'title_ru' => 'Галисийский',
    'locale' => 'gl_ES',
    'locales' => array('gl_ES'),
    'month' => array( 1 =>
      'Xaneiro',
      'Febreiro',
      'Marzo',
      'Abril',
      'Maio',
      'Xuño',
      'Xullo',
      'Agosto',
      'Setembro',
      'Outubro',
      'Novembro',
      'Decembro',
    ),
  ),
  'gu' => array(
    'title' => 'ગુજરાતી',
    'title_en' => 'Gujarati',
    'title_ru' => 'Гуджарати',
    'locale' => 'gu_IN',
    'locales' => array('gu_IN'),
    'month' => array( 1 =>
      'જાન્યુઆરી',
      'ફેબ્રુઆરી',
      'માર્ચ',
      'એપ્રિલ',
      'મે',
      'જૂન',
      'જુલાઈ',
      'ઑગસ્ટ',
      'સપ્ટેમ્બર',
      'ઑક્ટ્બર',
      'નવેમ્બર',
      'ડિસેમ્બર',
    ),
  ),
  'gv' => array(
    'title' => 'Gaelg',
    'title_en' => 'Manx',
    'title_ru' => 'Мэнский',
    'locale' => 'gv_GB',
    'locales' => array('gv_GB'),
    'month' => array( 1 =>
      'Jerrey-geuree',
      'Toshiaght-arree',
      'Mayrnt',
      'Averil',
      'Boaldyn',
      'Mean-souree',
      'Jerrey-souree',
      'Luanistyn',
      'Mean-fouyir',
      'Jerrey-fouyir',
      'Mee Houney',
      'Mee ny Nollick',
    ),
  ),
  'ha' => array(
    'title' => 'Hausa',
    'title_en' => 'Hausa',
    'title_ru' => 'Хауса',
    'locale' => 'ha_NG',
    'locales' => array('ha_NG'),
    'month' => array( 1 =>
      'Janairu',
      'Faburairu',
      'Maris',
      'Afirilu',
      'Mayu',
      'Yuni',
      'Yuli',
      'Agusta',
      'Satumba',
      'Oktoba',
      'Nuwamba',
      'Disamba',
    ),
  ),
  'he' => array(
    'title' => 'עברית',
    'title_en' => 'Hebrew',
    'title_ru' => 'Иврит',
    'locale' => 'he_IL',
    'locales' => array('he_IL'),
    'month' => array( 1 =>
      'ינואר',
      'פברואר',
      'מרץ',
      'אפריל',
      'מאי',
      'יוני',
      'יולי',
      'אוגוסט',
      'ספטמבר',
      'אוקטובר',
      'נובמבר',
      'דצמבר',
    ),
  ),
  'hi' => array(
    'title' => 'हिन्दी',
    'title_en' => 'Hindi',
    'title_ru' => 'Хинди',
    'locale' => 'hi_IN',
    'locales' => array('hi_IN'),
    'month' => array( 1 =>
      'जनवरी',
      'फरवरी',
      'मार्च',
      'अप्रैल',
      'मई',
      'जून',
      'जुलाई',
      'अगस्त',
      'सितम्बर',
      'अक्तूबर',
      'नवम्बर',
      'दिसम्बर',
    ),
  ),
  'hr' => array(
    'title' => 'Hrvatski',
    'title_en' => 'Croatian',
    'title_ru' => 'Хорватский',
    'locale' => 'hr_HR',
    'locales' => array('hr_HR'),
    'month' => array( 1 =>
      'siječanj',
      'veljača',
      'ožujak',
      'travanj',
      'svibanj',
      'lipanj',
      'srpanj',
      'kolovoz',
      'rujan',
      'listopad',
      'studeni',
      'prosinac',
    ),
  ),
  'hu' => array(
    'title' => 'Magyar',
    'title_en' => 'Hungarian',
    'title_ru' => 'Венгерский',
    'locale' => 'hu_HU',
    'locales' => array('hu_HU'),
    'month' => array( 1 =>
      'január',
      'február',
      'március',
      'április',
      'május',
      'június',
      'július',
      'augusztus',
      'szeptember',
      'október',
      'november',
      'december',
    ),
  ),
  'hy' => array(
    'title' => 'Հայերեն',
    'title_en' => 'Armenian',
    'title_ru' => 'Армянский',
    'locale' => 'hy_AM',
    'locales' => array('hy_AM'),
    'month' => array( 1 =>
      'հունվարի',
      'փետրվարի',
      'մարտի',
      'ապրիլի',
      'մայիսի',
      'հունիսի',
      'հուլիսի',
      'օգոստոսի',
      'սեպտեմբերի',
      'հոկտեմբերի',
      'նոյեմբերի',
      'դեկտեմբերի',
    ),
  ),
  'ia' => array(
    'title' => 'Interlingua',
    'title_en' => 'Interlingua',
    'title_ru' => 'Интерлингва',
    'locale' => 'ia_FR',
    'locales' => array('ia_FR'),
    'month' => array( 1 =>
      'januario',
      'februario',
      'martio',
      'april',
      'maio',
      'junio',
      'julio',
      'augusto',
      'septembre',
      'octobre',
      'novembre',
      'decembre',
    ),
  ),
  'id' => array(
    'title' => 'Bahasa Indonesia',
    'title_en' => 'Indonesian',
    'title_ru' => 'Индонезийский',
    'locale' => 'id_ID',
    'locales' => array('id_ID'),
    'month' => array( 1 =>
      'Januari',
      'Februari',
      'Maret',
      'April',
      'Mei',
      'Juni',
      'Juli',
      'Agustus',
      'September',
      'Oktober',
      'November',
      'Desember',
    ),
  ),
  'ig' => array(
    'title' => 'Igbo',
    'title_en' => 'Igbo',
    'title_ru' => 'Игбо',
    'locale' => 'ig_NG',
    'locales' => array('ig_NG'),
    'month' => array( 1 =>
      'Jenụwarị',
      'Febrụwarị',
      'Maachị',
      'Eprel',
      'Mee',
      'Juun',
      'Julaị',
      'Ọgọọst',
      'Septemba',
      'Ọktoba',
      'Novemba',
      'Disemba',
    ),
  ),
  'is' => array(
    'title' => 'Íslenska',
    'title_en' => 'Icelandic',
    'title_ru' => 'Исландский',
    'locale' => 'is_IS',
    'locales' => array('is_IS'),
    'month' => array( 1 =>
      'janúar',
      'febrúar',
      'mars',
      'apríl',
      'maí',
      'júní',
      'júlí',
      'ágúst',
      'september',
      'október',
      'nóvember',
      'desember',
    ),
  ),
  'it' => array(
    'title' => 'Italiano',
    'title_en' => 'Italian',
    'title_ru' => 'Итальянский',
    'locale' => 'it_IT',
    'locales' => array('it_CH','it_IT'),
    'month' => array( 1 =>
      'Gennaio',
      'Febbraio',
      'Marzo',
      'Aprile',
      'Maggio',
      'Giugno',
      'Luglio',
      'Agosto',
      'Settembre',
      'Ottobre',
      'Novembre',
      'Dicembre',
    ),
  ),
  'iu' => array(
    'title' => 'ᐃᓄᒃᑎᑐᑦ',
    'title_en' => 'Inuktitut',
    'title_ru' => 'Инуктитут',
    'locale' => 'iu_CA',
    'locales' => array('iu_CA'),
    'month' => array( 1 =>
      'ᔭᓐᓄᐊᓕ',
      'ᕕᕝᕗᐊᓕ',
      'ᒫᑦᓯ',
      'ᐊᐃᑉᐳᓗ',
      'ᒪᐃ',
      'ᔫᓂ',
      'ᔪᓚᐃ',
      'ᐊᐅᒡᒍᓯ',
      'ᓰᑦᑏᕝᕙ',
      'ᐆᑦᑑᕝᕙ',
      'ᓅᕙᐃᕝᕙ',
      'ᑏᓰᕝᕙ',
    ),
  ),
  'ja' => array(
    'title' => '日本語',
    'title_en' => 'Japanese',
    'title_ru' => 'Японский',
    'locale' => 'ja_JP',
    'locales' => array('ja_JP'),
    'month' => array( 1 =>
      '1月',
      '2月',
      '3月',
      '4月',
      '5月',
      '6月',
      '7月',
      '8月',
      '9月',
      '10月',
      '11月',
      '12月',
    ),
  ),
  'ka' => array(
    'title' => 'ქართული',
    'title_en' => 'Georgian',
    'title_ru' => 'Грузинский',
    'locale' => 'ka_GE',
    'locales' => array('ka_GE'),
    'month' => array( 1 =>
      'იანვარი',
      'თებერვალი',
      'მარტი',
      'აპრილი',
      'მაისი',
      'ივნისი',
      'ივლისი',
      'აგვისტო',
      'სექტემბერი',
      'ოქტომბერი',
      'ნოემბერი',
      'დეკემბერი',
    ),
  ),
  'kk' => array(
    'title' => 'Қазақ тілі',
    'title_en' => 'Kazakh',
    'title_ru' => 'Казахский',
    'locale' => 'kk_KZ',
    'locales' => array('kk_KZ'),
    'month' => array( 1 =>
      'қаңтар',
      'ақпан',
      'наурыз',
      'сәуір',
      'мамыр',
      'маусым',
      'шілде',
      'тамыз',
      'қыркүйек',
      'қазан',
      'қараша',
      'желтоқсан',
    ),
  ),
  'kl' => array(
    'title' => 'Kalaallisut',
    'title_en' => 'Greenlandic',
    'title_ru' => 'Гренландский',
    'locale' => 'kl_GL',
    'locales' => array('kl_GL'),
    'month' => array( 1 =>
      'januari',
      'februari',
      'martsi',
      'aprili',
      'maji',
      'juni',
      'juli',
      'augustusi',
      'septemberi',
      'oktoberi',
      'novemberi',
      'decemberi',
    ),
  ),
  'km' => array(
    'title' => 'ភាសាខ្មែរ',
    'title_en' => 'Khmer',
    'title_ru' => 'Кхмерский',
    'locale' => 'km_KH',
    'locales' => array('km_KH'),
    'month' => array( 1 =>
      'មករា',
      'កុម្ភៈ',
      'មីនា',
      'មេសា',
      'ឧសភា',
      'មិថុនា',
      'កក្កដា',
      'សីហា',
      'កញ្ញា',
      'តុលា',
      'វិច្ឆិកា',
      'ធ្នូ',
    ),
  ),
  'kn' => array(
    'title' => 'ಕನ್ನಡ',
    'title_en' => 'Kannada',
    'title_ru' => 'Каннада',
    'locale' => 'kn_IN',
    'locales' => array('kn_IN'),
    'month' => array( 1 =>
      'ಜನವರೀ',
      'ಫೆಬ್ರವರೀ',
      'ಮಾರ್ಚ್',
      'ಎಪ್ರಿಲ್',
      'ಮೆ',
      'ಜೂನ್',
      'ಜುಲೈ',
      'ಆಗಸ್ಟ್',
      'ಸಪ್ಟೆಂಬರ್',
      'ಅಕ್ಟೋಬರ್',
      'ನವೆಂಬರ್',
      'ಡಿಸೆಂಬರ್',
    ),
  ),
  'ko' => array(
    'title' => '한국어',
    'title_en' => 'Korean',
    'title_ru' => 'Корейский',
    'locale' => 'ko_KR',
    'locales' => array('ko_KR'),
    'month' => array( 1 =>
      '1월',
      '2월',
      '3월',
      '4월',
      '5월',
      '6월',
      '7월',
      '8월',
      '9월',
      '10월',
      '11월',
      '12월',
    ),
  ),
  'ks' => array(
    'title' => 'कश्मीरी‎',
    'title_en' => 'Kashmiri',
    'title_ru' => 'Кашмири',
    'locale' => 'ks_IN',
    'locales' => array('ks_IN'),
    'month' => array( 1 =>
      'جنؤری',
      'فرؤری',
      'مارٕچ',
      'اپریل',
      'میٔ',
      'جوٗن',
      'جوٗلایی',
      'اگست',
      'ستمبر',
      'اکتوٗبر',
      'نومبر',
      'دسمبر',
    ),
  ),
  'ku' => array(
    'title' => 'Kurdî',
    'title_en' => 'Kurdish',
    'title_ru' => 'Курдский',
    'locale' => 'ku_TR',
    'locales' => array('ku_TR'),
    'month' => array( 1 =>
      'کانوونی دووەم',
      'شوبات',
      'ئازار',
      'نیسان',
      'ئایار',
      'حوزەیران',
      'تەمووز',
      'ئاب',
      'ئەیلوول',
      'تشرینی یەکەم',
      'تشرینی دووەم',
      'کانونی یەکەم',
    ),
  ),
  'kw' => array(
    'title' => 'Kernewek',
    'title_en' => 'Cornish',
    'title_ru' => 'Корнский',
    'locale' => 'kw_GB',
    'locales' => array('kw_GB'),
    'month' => array( 1 =>
      'Mys Genver',
      'Mys Whevrel',
      'Mys Merth',
      'Mys Ebrel',
      'Mys Me',
      'Mys Efan',
      'Mys Gortheren',
      'Mye Est',
      'Mys Gwyngala',
      'Mys Hedra',
      'Mys Du',
      'Mys Kevardhu',
    ),
  ),
  'ky' => array(
    'title' => 'Кыргыз тили',
    'title_en' => 'Kyrgyz',
    'title_ru' => 'Киргизский',
    'locale' => 'ky_KG',
    'locales' => array('ky_KG'),
    'month' => array( 1 =>
      'Январь',
      'Февраль',
      'Март',
      'Апрель',
      'Май',
      'Июнь',
      'Июль',
      'Август',
      'Сентябрь',
      'Октябрь',
      'Ноябрь',
      'Декабрь',
    ),
  ),
  'lg' => array(
    'title' => 'Luganda',
    'title_en' => 'Luganda',
    'title_ru' => 'Луганда',
    'locale' => 'lg_UG',
    'locales' => array('lg_UG'),
    'month' => array( 1 =>
      'Janwaliyo',
      'Febwaliyo',
      'Marisi',
      'Apuli',
      'Maayi',
      'Juuni',
      'Julaayi',
      'Agusito',
      'Sebuttemba',
      'Okitobba',
      'Novemba',
      'Desemba',
    ),
  ),
  'lo' => array(
    'title' => 'ພາສາລາວ',
    'title_en' => 'Lao',
    'title_ru' => 'Лаосский',
    'locale' => 'lo_LA',
    'locales' => array('lo_LA'),
    'month' => array( 1 =>
      'ມັງກອນ',
      'ກຸມພາ',
      'ມີນາ',
      'ເມສາ',
      'ພຶດສະພາ',
      'ມິຖຸນາ',
      'ກໍລະກົດ',
      'ສິງຫາ',
      'ກັນຍາ',
      'ຕຸລາ',
      'ພະຈິກ',
      'ທັນວາ',
    ),
  ),
  'lt' => array(
    'title' => 'Lietuvių kalba',
    'title_en' => 'Lithuanian',
    'title_ru' => 'Литовский',
    'locale' => 'lt_LT',
    'locales' => array('lt_LT'),
    'month' => array( 1 =>
      'sausis',
      'vasaris',
      'kovas',
      'balandis',
      'gegužė',
      'birželis',
      'liepa',
      'rugpjūtis',
      'rugsėjis',
      'spalis',
      'lapkritis',
      'gruodis',
    ),
  ),
  'lv' => array(
    'title' => 'Latviešu valoda',
    'title_en' => 'Latvian',
    'title_ru' => 'Латышский',
    'locale' => 'lv_LV',
    'locales' => array('lv_LV'),
    'month' => array( 1 =>
      'Janvāris',
      'Februāris',
      'Marts',
      'Aprīlis',
      'Maijs',
      'Jūnijs',
      'Jūlijs',
      'Augusts',
      'Septembris',
      'Oktobris',
      'Novembris',
      'Decembris',
    ),
  ),
  'mg' => array(
    'title' => 'Malagasy fiteny',
    'title_en' => 'Malagasy',
    'title_ru' => 'Малагасийский',
    'locale' => 'mg_MG',
    'locales' => array('mg_MG'),
    'month' => array( 1 =>
      'Janoary',
      'Febroary',
      'Martsa',
      'Aprily',
      'Mey',
      'Jona',
      'Jolay',
      'Aogositra',
      'Septambra',
      'Oktobra',
      'Novambra',
      'Desambra',
    ),
  ),
  'mi' => array(
    'title' => 'Māori',
    'title_en' => 'Māori',
    'title_ru' => 'Маори',
    'locale' => 'mi_NZ',
    'locales' => array('mi_NZ'),
    'month' => array( 1 =>
      'Hānuere',
      'Pēpuere',
      'Māehe',
      'Āperira',
      'Mei',
      'Hune',
      'Hūrae',
      'Ākuhata',
      'Hepetema',
      'Oketopa',
      'Noema',
      'Tīhema',
    ),
  ),
  'mk' => array(
    'title' => 'Македонски',
    'title_en' => 'Macedonian',
    'title_ru' => 'Македонский',
    'locale' => 'mk_MK',
    'locales' => array('mk_MK'),
    'month' => array( 1 =>
      'јануари',
      'февруари',
      'март',
      'април',
      'мај',
      'јуни',
      'јули',
      'август',
      'септември',
      'октомври',
      'ноември',
      'декември',
    ),
  ),
  'ml' => array(
    'title' => 'മലയാളം',
    'title_en' => 'Malayalam',
    'title_ru' => 'Малаялам',
    'locale' => 'ml_IN',
    'locales' => array('ml_IN'),
    'month' => array( 1 =>
      'ജനുവരി',
      'ഫെബ്രുവരി',
      'മാർച്ച്',
      'ഏപ്രിൽ',
      'മേയ്',
      'ജൂൺ',
      'ജൂലൈ',
      'ആഗസ്റ്റ്',
      'സെപ്റ്റംബർ',
      'ഒക്ടോബർ',
      'നവംബർ',
      'ഡിസംബർ',
    ),
  ),
  'mn' => array(
    'title' => 'Монгол',
    'title_en' => 'Mongolian',
    'title_ru' => 'Монгольский',
    'locale' => 'mn_MN',
    'locales' => array('mn_MN'),
    'month' => array( 1 =>
      '1сарын',
      '2сарын',
      '3сарын',
      '4сарын',
      '5сарын',
      '6сарын',
      '7сарын',
      '8сарын',
      '9сарын',
      '10сарын',
      '11сарын',
      '12сарын',
    ),
  ),
  'mr' => array(
    'title' => 'मराठी',
    'title_en' => 'Marathi',
    'title_ru' => 'Маратхи',
    'locale' => 'mr_IN',
    'locales' => array('mr_IN'),
    'month' => array( 1 =>
      'जानेवारी',
      'फेब्रुवारी',
      'मार्च',
      'एप्रिल',
      'मे',
      'जून',
      'जुलै',
      'ऑगस्ट',
      'सप्टेंबर',
      'ऑक्टोबर',
      'नोव्हेंबर',
      'डिसेंबर',
    ),
  ),
  'ms' => array(
    'title' => 'Bahasa Melayu, بهاس ملايو‎',
    'title_en' => 'Malay',
    'title_ru' => 'Малайский',
    'locale' => 'ms_MY',
    'locales' => array('ms_MY'),
    'month' => array( 1 =>
      'Januari',
      'Februari',
      'Mac',
      'April',
      'Mei',
      'Jun',
      'Julai',
      'Ogos',
      'September',
      'Oktober',
      'November',
      'Disember',
    ),
  ),
  'mt' => array(
    'title' => 'Malti',
    'title_en' => 'Maltese',
    'title_ru' => 'Мальтийский',
    'locale' => 'mt_MT',
    'locales' => array('mt_MT'),
    'month' => array( 1 =>
      'Jannar',
      'Frar',
      'Marzu',
      'April',
      'Mejju',
      'Ġunju',
      'Lulju',
      'Awwissu',
      'Settembru',
      'Ottubru',
      'Novembru',
      'Diċembru',
    ),
  ),
  'my' => array(
    'title' => 'ဗမာစာ',
    'title_en' => 'Burmese',
    'title_ru' => 'Бирманский',
    'locale' => 'my_MM',
    'locales' => array('my_MM'),
    'month' => array( 1 =>
      'ဇန်နဝါရီ',
      'ဖေဖော်ဝါရီ',
      'မတ်',
      'ဧပြီ',
      'မေ',
      'ဇွန်',
      'ဇူလိုင်',
      'ဩဂုတ်',
      'စက်တင်ဘာ',
      'အောက်တိုဘာ',
      'နိုဝင်ဘာ',
      'ဒီဇင်ဘာ',
    ),
  ),
  'nb' => array(
    'title' => 'Norsk bokmål',
    'title_en' => 'Norwegian Bokmål',
    'title_ru' => 'Букмол',
    'locale' => 'nb_NO',
    'locales' => array('nb_NO'),
    'month' => array( 1 =>
      'januar',
      'februar',
      'mars',
      'april',
      'mai',
      'juni',
      'juli',
      'august',
      'september',
      'oktober',
      'november',
      'desember',
    ),
  ),
  'ne' => array(
    'title' => 'नेपाली',
    'title_en' => 'Nepali',
    'title_ru' => 'Непальский',
    'locale' => 'ne_NP',
    'locales' => array('ne_NP'),
    'month' => array( 1 =>
      'जनवरी',
      'फेब्रुअरी',
      'मार्च',
      'अप्रिल',
      'मे',
      'जुन',
      'जुलाई',
      'अगस्ट',
      'सेप्टेम्बर',
      'अक्टोबर',
      'नोभेम्बर',
      'डिसेम्बर',
    ),
  ),
  'nl' => array(
    'title' => 'Nederlands, Vlaams',
    'title_en' => 'Dutch',
    'title_ru' => 'Нидерландский',
    'locale' => 'nl_NL',
    'locales' => array('nl_AW','nl_BE','nl_NL'),
    'month' => array( 1 =>
      'januari',
      'februari',
      'maart',
      'april',
      'mei',
      'juni',
      'juli',
      'augustus',
      'september',
      'oktober',
      'november',
      'december',
    ),
  ),
  'nn' => array(
    'title' => 'Norsk nynorsk',
    'title_en' => 'Norwegian Nynorsk',
    'title_ru' => 'Нюнорск',
    'locale' => 'nn_NO',
    'locales' => array('nn_NO'),
    'month' => array( 1 =>
      'januar',
      'februar',
      'mars',
      'april',
      'mai',
      'juni',
      'juli',
      'august',
      'september',
      'oktober',
      'november',
      'desember',
    ),
  ),
  'no' => array(
    'title' => 'Norsk',
    'title_en' => 'Norwegian',
    'title_ru' => 'Норвежский',
    'locale' => 'no_NO',
    'locales' => array('no_NO'),
    'month' => array( 1 =>
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
    ),
  ),
  'nr' => array(
    'title' => 'isiNdebele',
    'title_en' => 'South Ndebele',
    'title_ru' => 'Ндебеле южный',
    'locale' => 'nr_ZA',
    'locales' => array('nr_ZA'),
    'month' => array( 1 =>
      'Janabari',
      'uFeberbari',
      'uMatjhi',
      'u-Apreli',
      'Meyi',
      'Juni',
      'Julayi',
      'Arhostosi',
      'Septemba',
      'Oktoba',
      'Usinyikhaba',
      'Disemba',
    ),
  ),
  'oc' => array(
    'title' => 'Occitan',
    'title_en' => 'Occitan',
    'title_ru' => 'Окситанский',
    'locale' => 'oc_FR',
    'locales' => array('oc_FR'),
    'month' => array( 1 =>
      'genièr',
      'febrièr',
      'març',
      'abril',
      'mai',
      'junh',
      'julhet',
      'agost',
      'setembre',
      'octòbre',
      'novembre',
      'dezembre',
    ),
  ),
  'om' => array(
    'title' => 'Afaan Oromoo',
    'title_en' => 'Oromo',
    'title_ru' => 'Оромо',
    'locale' => 'om_ET',
    'locales' => array('om_ET','om_KE'),
    'month' => array( 1 =>
      'Amajjii',
      'Guraandhala',
      'Bitooteessa',
      'Elba',
      'Caamsa',
      'Waxabajjii',
      'Adooleessa',
      'Hagayya',
      'Fuulbana',
      'Onkololeessa',
      'Sadaasa',
      'Muddee',
    ),
  ),
  'or' => array(
    'title' => 'ଓଡ଼ିଆ',
    'title_en' => 'Oriya',
    'title_ru' => 'Ория',
    'locale' => 'or_IN',
    'locales' => array('or_IN'),
    'month' => array( 1 =>
      'ଜାନୁଆରୀ',
      'ଫେବ୍ରୁୟାରୀ',
      'ମାର୍ଚ୍ଚ',
      'ଅପ୍ରେଲ',
      'ମେ',
      'ଜୁନ',
      'ଜୁଲାଇ',
      'ଅଗଷ୍ଟ',
      'ସେପ୍ଟେମ୍ବର',
      'ଅକ୍ଟୋବର',
      'ନଭେମ୍ବର',
      'ଡିସେମ୍ବର',
    ),
  ),
  'os' => array(
    'title' => 'Ирон æвзаг',
    'title_en' => 'Ossetian',
    'title_ru' => 'Осетинский',
    'locale' => 'os_RU',
    'locales' => array('os_RU'),
    'month' => array( 1 =>
      'Январь',
      'Февраль',
      'Мартъи',
      'Апрель',
      'Май',
      'Июнь',
      'Июль',
      'Август',
      'Сентябрь',
      'Октябрь',
      'Ноябрь',
      'Декабрь',
    ),
  ),
  'pa' => array(
    'title' => 'ਪੰਜਾਬੀ',
    'title_en' => 'Panjabi',
    'title_ru' => 'Пенджабский',
    'locale' => 'pa_PK',
    'locales' => array('pa_IN','pa_PK'),
    'month' => array( 1 =>
      'ਜਨਵਰੀ',
      'ਫ਼ਰਵਰੀ',
      'ਮਾਰਚ',
      'ਅਪ੍ਰੈਲ',
      'ਮਈ',
      'ਜੂਨ',
      'ਜੁਲਾਈ',
      'ਅਗਸਤ',
      'ਸਤੰਬਰ',
      'ਅਕਤੂਬਰ',
      'ਨਵੰਬਰ',
      'ਦਸੰਬਰ',
    ),
  ),
  'pl' => array(
    'title' => 'Polski',
    'title_en' => 'Polish',
    'title_ru' => 'Польский',
    'locale' => 'pl_PL',
    'locales' => array('pl_PL'),
    'month' => array( 1 =>
      'styczeń',
      'luty',
      'marzec',
      'kwiecień',
      'maj',
      'czerwiec',
      'lipiec',
      'sierpień',
      'wrzesień',
      'październik',
      'listopad',
      'grudzień',
    ),
  ),
  'ps' => array(
    'title' => 'پښتو',
    'title_en' => 'Pashto',
    'title_ru' => 'Пушту',
    'locale' => 'ps_AF',
    'locales' => array('ps_AF'),
    'month' => array( 1 =>
      'جنوري',
      'فبروري',
      'مارچ',
      'اپریل',
      'می',
      'جون',
      'جولای',
      'اګست',
      'سپتمبر',
      'اکتوبر',
      'نومبر',
      'دسمبر',
    ),
  ),
  'pt' => array(
    'title' => 'Português',
    'title_en' => 'Portuguese',
    'title_ru' => 'Португальский',
    'locale' => 'pt_BR',
    'locales' => array('pt_BR','pt_PT'),
    'month' => array( 1 =>
      'janeiro',
      'fevereiro',
      'março',
      'abril',
      'maio',
      'junho',
      'julho',
      'agosto',
      'setembro',
      'outubro',
      'novembro',
      'dezembro',
    ),
  ),
  'ro' => array(
    'title' => 'Română',
    'title_en' => 'Romanian',
    'title_ru' => 'Румынский',
    'locale' => 'ro_RO',
    'locales' => array('ro_RO'),
    'month' => array( 1 =>
      'ianuarie',
      'februarie',
      'martie',
      'aprilie',
      'mai',
      'iunie',
      'iulie',
      'august',
      'septembrie',
      'octombrie',
      'noiembrie',
      'decembrie',
    ),
  ),
  'ru' => array(
    'title' => 'Русский',
    'title_en' => 'Russian',
    'title_ru' => 'Русский',
    'locale' => 'ru_RU',
    'locales' => array('ru_RU','ru_UA'),
    'month' => array( 1 =>
      'января',
      'февраля',
      'марта',
      'апреля',
      'мая',
      'июня',
      'июля',
      'августа',
      'сентября',
      'октября',
      'ноября',
      'декабря',
    ),
  ),
  'rw' => array(
    'title' => 'Ikinyarwanda',
    'title_en' => 'Kinyarwanda',
    'title_ru' => 'Руанда',
    'locale' => 'rw_RW',
    'locales' => array('rw_RW'),
    'month' => array( 1 =>
      'Mutarama',
      'Gashyantare',
      'Werurwe',
      'Mata',
      'Gicuransi',
      'Kamena',
      'Nyakanga',
      'Kanama',
      'Nzeli',
      'Ukwakira',
      'Ugushyingo',
      'Ukuboza',
    ),
  ),
  'sa' => array(
    'title' => 'संस्कृतम्',
    'title_en' => 'Sanskrit',
    'title_ru' => 'Санскрит',
    'locale' => 'sa_IN',
    'locales' => array('sa_IN'),
    'month' => array( 1 =>
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
    ),
  ),
  'se' => array(
    'title' => 'Davvisámegiella',
    'title_en' => 'Northern Sami',
    'title_ru' => 'Северносаамский',
    'locale' => 'se_NO',
    'locales' => array('se_NO'),
    'month' => array( 1 =>
      'ođđajagemánnu',
      'guovvamánnu',
      'njukčamánnu',
      'cuoŋománnu',
      'miessemánnu',
      'geassemánnu',
      'suoidnemánnu',
      'borgemánnu',
      'čakčamánnu',
      'golggotmánnu',
      'skábmamánnu',
      'juovlamánnu',
    ),
  ),
  'si' => array(
    'title' => 'සිංහල',
    'title_en' => 'Sinhalese',
    'title_ru' => 'Сингальский',
    'locale' => 'si_LK',
    'locales' => array('si_LK'),
    'month' => array( 1 =>
      'ජනවාරි',
      'පෙබරවාරි',
      'මාර්තු',
      'අප්‍රේල්',
      'මැයි',
      'ජූනි',
      'ජූලි',
      'අගෝස්තු',
      'සැප්තැම්බර්',
      'ඔක්තෝබර්',
      'නොවැම්බර්',
      'දෙසැම්බර්',
    ),
  ),
  'sk' => array(
    'title' => 'Slovenčina',
    'title_en' => 'Slovak',
    'title_ru' => 'Словацкий',
    'locale' => 'sk_SK',
    'locales' => array('sk_SK'),
    'month' => array( 1 =>
      'január',
      'február',
      'marec',
      'apríl',
      'máj',
      'jún',
      'júl',
      'august',
      'september',
      'október',
      'november',
      'december',
    ),
  ),
  'sl' => array(
    'title' => 'Slovenščina',
    'title_en' => 'Slovene',
    'title_ru' => 'Словенский',
    'locale' => 'sl_SI',
    'locales' => array('sl_SI'),
    'month' => array( 1 =>
      'januar',
      'februar',
      'marec',
      'april',
      'maj',
      'junij',
      'julij',
      'avgust',
      'september',
      'oktober',
      'november',
      'december',
    ),
  ),
  'so' => array(
    'title' => 'Soomaaliga',
    'title_en' => 'Somali',
    'title_ru' => 'Сомали',
    'locale' => 'so_SO',
    'locales' => array('so_DJ','so_ET','so_KE','so_SO'),
    'month' => array( 1 =>
      'Bisha Koobaad',
      'Bisha Labaad',
      'Bisha Saddexaad',
      'Bisha Afraad',
      'Bisha Shanaad',
      'Bisha Lixaad',
      'Bisha Todobaad',
      'Bisha Sideedaad',
      'Bisha Sagaalaad',
      'Bisha Tobnaad',
      'Bisha Kow iyo Tobnaad',
      'Bisha Laba iyo Tobnaad',
    ),
  ),
  'sq' => array(
    'title' => 'Shqip',
    'title_en' => 'Albanian',
    'title_ru' => 'Албанский',
    'locale' => 'sq_AL',
    'locales' => array('sq_AL','sq_MK'),
    'month' => array( 1 =>
      'janar',
      'shkurt',
      'mars',
      'prill',
      'maj',
      'qershor',
      'korrik',
      'gusht',
      'shtator',
      'tetor',
      'nëntor',
      'dhjetor',
    ),
  ),
  'sr' => array(
    'title' => 'Српски језик',
    'title_en' => 'Serbian',
    'title_ru' => 'Сербский',
    'locale' => 'sr_RS',
    'locales' => array('sr_ME','sr_RS'),
    'month' => array( 1 =>
      'јануар',
      'фебруар',
      'март',
      'април',
      'мај',
      'јун',
      'јул',
      'август',
      'септембар',
      'октобар',
      'новембар',
      'децембар',
    ),
  ),
  'ss' => array(
    'title' => 'SiSwati',
    'title_en' => 'Swati',
    'title_ru' => 'Свази',
    'locale' => 'ss_ZA',
    'locales' => array('ss_ZA'),
    'month' => array( 1 =>
      'Bhimbidvwane',
      'iNdlovana',
      'iNdlovu-lenkhulu',
      'Mabasa',
      'iNkhwekhweti',
      'iNhlaba',
      'Kholwane',
      'iNgci',
      'iNyoni',
      'iMphala',
      'Lweti',
      'iNgongoni',
    ),
  ),
  'st' => array(
    'title' => 'Sesotho',
    'title_en' => 'Southern Sotho',
    'title_ru' => 'Сото южный',
    'locale' => 'st_ZA',
    'locales' => array('st_ZA'),
    'month' => array( 1 =>
      'Phesekgong',
      'Hlakola',
      'Hlakubele',
      'Mmese',
      'Motsheanong',
      'Phupjane',
      'Phupu',
      'Phata',
      'Leotshe',
      'Mphalane',
      'Pundungwane',
      'Tshitwe',
    ),
  ),
  'sv' => array(
    'title' => 'Svenska',
    'title_en' => 'Swedish',
    'title_ru' => 'Шведский',
    'locale' => 'sv_SE',
    'locales' => array('sv_FI','sv_SE'),
    'month' => array( 1 =>
      'Januari',
      'Februari',
      'Mars',
      'April',
      'Maj',
      'Juni',
      'Juli',
      'Augusti',
      'September',
      'Oktober',
      'November',
      'December',
    ),
  ),
  'sw' => array(
    'title' => 'Kiswahili',
    'title_en' => 'Swahili',
    'title_ru' => 'Суахили',
    'locale' => 'sw_TZ',
    'locales' => array('sw_KE','sw_TZ'),
    'month' => array( 1 =>
      'Januari',
      'Februari',
      'Machi',
      'Aprili',
      'Mei',
      'Juni',
      'Julai',
      'Agosti',
      'Septemba',
      'Oktoba',
      'Novemba',
      'Desemba',
    ),
  ),
  'ta' => array(
    'title' => 'தமிழ்',
    'title_en' => 'Tamil',
    'title_ru' => 'Тамильский',
    'locale' => 'ta_IN',
    'locales' => array('ta_IN','ta_LK'),
    'month' => array( 1 =>
      'ஜனவரி',
      'பிப்ரவரி',
      'மார்ச்',
      'ஏப்ரல்',
      'மே',
      'ஜூன்',
      'ஜூலை',
      'ஆகஸ்டு',
      'செப்டம்பர்',
      'அக்டோபர்',
      'நவம்பர்',
      'டிசம்பர்',
    ),
  ),
  'te' => array(
    'title' => 'తెలుగు',
    'title_en' => 'Telugu',
    'title_ru' => 'Телугу',
    'locale' => 'te_IN',
    'locales' => array('te_IN'),
    'month' => array( 1 =>
      'జనవరి',
      'ఫిబ్రవరి',
      'మార్చి',
      'ఎప్రిల్',
      'మే',
      'జూన్',
      'జూలై',
      'ఆగస్టు',
      'సెప్టెంబర్',
      'అక్టోబర్',
      'నవంబర్',
      'డిసెంబర్',
    ),
  ),
  'tg' => array(
    'title' => 'Тоҷикӣ',
    'title_en' => 'Tajik',
    'title_ru' => 'Таджикский',
    'locale' => 'tg_TJ',
    'locales' => array('tg_TJ'),
    'month' => array( 1 =>
      'Январ',
      'Феврал',
      'Март',
      'Апрел',
      'Май',
      'Июн',
      'Июл',
      'Август',
      'Сентябр',
      'Октябр',
      'Ноябр',
      'Декабр',
    ),
  ),
  'th' => array(
    'title' => 'ไทย',
    'title_en' => 'Thai',
    'title_ru' => 'Тайский',
    'locale' => 'th_TH',
    'locales' => array('th_TH'),
    'month' => array( 1 =>
      'มกราคม',
      'กุมภาพันธ์',
      'มีนาคม',
      'เมษายน',
      'พฤษภาคม',
      'มิถุนายน',
      'กรกฎาคม',
      'สิงหาคม',
      'กันยายน',
      'ตุลาคม',
      'พฤศจิกายน',
      'ธันวาคม',
    ),
  ),
  'ti' => array(
    'title' => 'ትግርኛ',
    'title_en' => 'Tigrinya',
    'title_ru' => 'Тигринья',
    'locale' => 'ti_ER',
    'locales' => array('ti_ER','ti_ET'),
    'month' => array( 1 =>
      'ጃንዩወሪ',
      'ፌብሩወሪ',
      'ማርች',
      'ኤፕረል',
      'ሜይ',
      'ጁን',
      'ጁላይ',
      'ኦገስት',
      'ሴፕቴምበር',
      'ኦክተውበር',
      'ኖቬምበር',
      'ዲሴምበር',
    ),
  ),
  'tl' => array(
    'title' => 'Tagalog',
    'title_en' => 'Tagalog',
    'title_ru' => 'Тагальский',
    'locale' => 'tl_PH',
    'locales' => array('tl_PH'),
    'month' => array( 1 =>
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
    ),
  ),
  'tn' => array(
    'title' => 'Setswana',
    'title_en' => 'Tswana',
    'title_ru' => 'Тсвана',
    'locale' => 'tn_ZA',
    'locales' => array('tn_ZA'),
    'month' => array( 1 =>
      'Ferikgong',
      'Tlhakole',
      'Mopitlo',
      'Moranang',
      'Motsheganang',
      'Seetebosigo',
      'Phukwi',
      'Phatwe',
      'Lwetse',
      'Diphalane',
      'Ngwanatsele',
      'Sedimonthole',
    ),
  ),
  'tr' => array(
    'title' => 'Türkçe',
    'title_en' => 'Turkish',
    'title_ru' => 'Турецкий',
    'locale' => 'tr_TR',
    'locales' => array('tr_CY','tr_TR'),
    'month' => array( 1 =>
      'Ocak',
      'Şubat',
      'Mart',
      'Nisan',
      'Mayıs',
      'Haziran',
      'Temmuz',
      'Ağustos',
      'Eylül',
      'Ekim',
      'Kasım',
      'Aralık',
    ),
  ),
  'ts' => array(
    'title' => 'Xitsonga',
    'title_en' => 'Tsonga',
    'title_ru' => 'Тсонга',
    'locale' => 'ts_ZA',
    'locales' => array('ts_ZA'),
    'month' => array( 1 =>
      'Sunguti',
      'Nyenyenyani',
      'Nyenyankulu',
      'Dzivamisoko',
      'Mudyaxihi',
      'Khotavuxika',
      'Mawuwani',
      'Mhawuri',
      'Ndzhati',
      'Nhlangula',
      'Hukuri',
      'N\'wendzamhala',
    ),
  ),
  'tt' => array(
    'title' => 'Татарча',
    'title_en' => 'Tatar',
    'title_ru' => 'Татарский',
    'locale' => 'tt_RU',
    'locales' => array('tt_RU'),
    'month' => array( 1 =>
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
    ),
  ),
  'ug' => array(
    'title' => 'Uyƣurqə‎',
    'title_en' => 'Uyghur',
    'title_ru' => 'Уйгурский',
    'locale' => 'ug_CN',
    'locales' => array('ug_CN'),
    'month' => array( 1 =>
      'يانۋار',
      'فېۋرال',
      'مارت',
      'ئاپرېل',
      'ماي',
      'ئىيۇن',
      'ئىيۇل',
      'ئاۋغۇست',
      'سېنتەبىر',
      'ئۆكتەبىر',
      'بويابىر',
      'دېكابىر',
    ),
  ),
  'uk' => array(
    'title' => 'Українська',
    'title_en' => 'Ukrainian',
    'title_ru' => 'Украинский',
    'locale' => 'uk_UA',
    'locales' => array('uk_UA'),
    'month' => array( 1 =>
      'січня',
      'лютого',
      'березня',
      'квітня',
      'травня',
      'червня',
      'липня',
      'серпня',
      'вересня',
      'жовтня',
      'листопада',
      'грудня',
    ),
  ),
  'ur' => array(
    'title' => 'اردو',
    'title_en' => 'Urdu',
    'title_ru' => 'Урду',
    'locale' => 'ur_IN',
    'locales' => array('ur_IN','ur_PK'),
    'month' => array( 1 =>
      'جنوری',
      'فروری',
      'مارچ',
      'اپریل',
      'مئ',
      'جون',
      'جولائ',
      'اگست',
      'ستمبر',
      'اکتوبر',
      'نومبر',
      'دسمبر',
    ),
  ),
  'uz' => array(
    'title' => 'Ўзбек‎',
    'title_en' => 'Uzbek',
    'title_ru' => 'Узбекский',
    'locale' => 'uz_UZ',
    'locales' => array('uz_UZ'),
    'month' => array( 1 =>
      'Январ',
      'Феврал',
      'Март',
      'Апрел',
      'Май',
      'Июн',
      'Июл',
      'Август',
      'Сентябр',
      'Октябр',
      'Ноябр',
      'Декабр',
    ),
  ),
  've' => array(
    'title' => 'Tshivenḓa',
    'title_en' => 'Venda',
    'title_ru' => 'Венда',
    'locale' => 've_ZA',
    'locales' => array('ve_ZA'),
    'month' => array( 1 =>
      'Phando',
      'Luhuhi',
      'Ṱhafamuhwe',
      'Lambamai',
      'Shundunthule',
      'Fulwi',
      'Fulwana',
      'Ṱhangule',
      'Khubvumedzi',
      'Tshimedzi',
      'Ḽara',
      'Nyendavhusiku',
    ),
  ),
  'vi' => array(
    'title' => 'Tiếng Việt',
    'title_en' => 'Vietnamese',
    'title_ru' => 'Вьетнамский',
    'locale' => 'vi_VN',
    'locales' => array('vi_VN'),
    'month' => array( 1 =>
      'tháng một',
      'tháng hai',
      'tháng ba',
      'tháng tư',
      'tháng năm',
      'tháng sáu',
      'tháng bảy',
      'tháng tám',
      'tháng chín',
      'tháng mười',
      'tháng mười một',
      'tháng mười hai',
    ),
  ),
  'wo' => array(
    'title' => 'Wollof',
    'title_en' => 'Wolof',
    'title_ru' => 'Волоф',
    'locale' => 'wo_SN',
    'locales' => array('wo_SN'),
    'month' => array( 1 =>
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '10',
      '11',
      '12',
    ),
  ),
  'xh' => array(
    'title' => 'isiXhosa',
    'title_en' => 'Xhosa',
    'title_ru' => 'Коса',
    'locale' => 'xh_ZA',
    'locales' => array('xh_ZA'),
    'month' => array( 1 =>
      'Janyuwari',
      'Februwari',
      'Matshi',
      'Epreli',
      'Meyi',
      'Juni',
      'Julayi',
      'Agasti',
      'Septemba',
      'Okthoba',
      'Novemba',
      'Disemba',
    ),
  ),
  'yo' => array(
    'title' => 'Yorùbá',
    'title_en' => 'Yoruba',
    'title_ru' => 'Йоруба',
    'locale' => 'yo_NG',
    'locales' => array('yo_NG'),
    'month' => array( 1 =>
      'Oṣù Ṣẹ́rẹ́',
      'Oṣù Èrèlè',
      'Oṣù Ẹrẹ̀nà',
      'Oṣù Ìgbé',
      'Oṣù Ẹ̀bibi',
      'Oṣù Òkúdu',
      'Oṣù Agẹmọ',
      'Oṣù Ògún',
      'Oṣù Owewe',
      'Oṣù Ọ̀wàrà',
      'Oṣù Bélú',
      'Oṣù Ọ̀pẹ̀',
    ),
  ),
  'zh' => array(
    'title' => '中文 (Zhōngwén)',
    'title_en' => 'Chinese',
    'title_ru' => 'Китайский',
    'locale' => 'zh_CN',
    'locales' => array('zh_CN','zh_HK','zh_SG','zh_TW'),
    'month' => array( 1 =>
      '一月',
      '二月',
      '三月',
      '四月',
      '五月',
      '六月',
      '七月',
      '八月',
      '九月',
      '十月',
      '十一月',
      '十二月',
    ),
  ),
);
